---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  # - iperf
  - libevent
  - sqlite
  # - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  # - pv
  - wget
  # - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask
# 
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - chromedriver
  - docker
  - dropbox
  # - firefox
  - google-chrome
  - brave-browser
  # - handbrake
  # - licecap
  # - sequel-pro
  # - slack
  # - sublime-text
  # - transmit
  - vagrant
  - iterm2
  - notion
  - spotify
  - visual-studio-code
  - cheatsheet
  # - kindle
  - postman
  - qv2ray
  # - virtualbox
  # - vmware-fusion
  # - whatsapp

pip_install_packages:
  - name: yfinance
    state: latest
  - name: pandas
    state: latest
  - name: numpy
    state: latest
  - name: boto3
    state: latest
  - name: beautifulsoup4
    state: latest
  - name: requests
    state: latest
  - name: openpyxl
    state: latest
  - name: google-api-python-client
    state: latest
  - name: google-auth-httplib2
    state: latest
  - name: google-auth-oauthlib
    state: latest
  - name: gspread
    state: latest
  - name: df2gspread
    state: latest
  - name: flask
    state: latest
