---
- hosts: all
  
  vars_files:
    - config.yml


  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml" #playbook_dir is a special variable that was passed to the `ansible_playbook` command line
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: homebrew
      tags: ['homebrew']
    - role: huang.pip
      tags: ['pip']